server:
  port: 8080
  mode: debug # debug, release, test
  read_timeout: 60s
  write_timeout: 60s

database:
  driver: mysql
  host: 117.72.204.201
  port: 3306
  username: root
  password: "njjzwljsyxgs"
  dbname: vista
  charset: utf8mb4
  parse_time: true
  loc: Local
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600s

wechat:
  app_id: "wx103412583eab4dfd"
  app_secret: "61cc794ea07bc5d41583ade5a143da49"
  redirect_uri: "https://carture.matrix-net.tech/wechat/callback"
  auth_domain: "carture.matrix-net.tech"