package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"vista/graph/model"
)

// WechatAuthCallback is the resolver for the wechatAuthCallback field.
func (r *mutationResolver) WechatAuthCallback(ctx context.Context, code string) (*model.WechatAuth, error) {
	// 模拟微信授权回调逻辑
	scope := "snsapi_userinfo"
	return &model.WechatAuth{
		Openid:      "mock_openid_" + code,
		AccessToken: "mock_access_token",
		ExpiresIn:   7200,
		Scope:       &scope,
		CreatedAt:   "2024-01-01T00:00:00Z",
		UpdatedAt:   "2024-01-01T00:00:00Z",
	}, nil
}

// WechatAuth is the resolver for the wechatAuth field.
func (r *queryResolver) WechatAuth(ctx context.Context, openid string) (*model.WechatAuth, error) {
	// 模拟根据 openid 查询微信授权信息
	scope := "snsapi_userinfo"
	return &model.WechatAuth{
		Openid:      openid,
		AccessToken: "mock_access_token",
		ExpiresIn:   7200,
		Scope:       &scope,
		CreatedAt:   "2024-01-01T00:00:00Z",
		UpdatedAt:   "2024-01-01T00:00:00Z",
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
