// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type WechatAuth struct {
	Openid       string  `json:"openid"`
	Unionid      *string `json:"unionid,omitempty"`
	AccessToken  string  `json:"accessToken"`
	ExpiresIn    int32   `json:"expiresIn"`
	RefreshToken *string `json:"refreshToken,omitempty"`
	Scope        *string `json:"scope,omitempty"`
	CreatedAt    string  `json:"createdAt"`
	UpdatedAt    string  `json:"updatedAt"`
}
